from . import student
from . import department
from . import class_model
from . import teacher
from . import subject
from . import academic_year
from . import semester
from . import enrollment
from . import grade
